
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msasycggbiwyxlczknwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zYXN5Y2dnYml3eXhsY3prbndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNjU5MTMsImV4cCI6MjA1Mjk0MTkxM30.Ezb5GjSg8ApUWR5iNMvVS9bSA7oxudUuYOP2g2ugB_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Currency utilities
export const getCurrencyForCountry = (country: string): string => {
  const currencyMap: { [key: string]: string } = {
    "Cameroun": "XAF",
    "Cameroon": "XAF",
    "Gabon": "XAF",
    "République centrafricaine": "XAF",
    "Tchad": "XAF",
    "Congo Brazzaville": "XAF",
    "Guinée équatoriale": "XAF",
    "Sénégal": "XOF",
    "Mali": "XOF",
    "Burkina Faso": "XOF",
    "Côte d'Ivoire": "XOF",
    "Niger": "XOF",
    "Togo": "XOF",
    "Bénin": "XOF",
    "Guinée-Bissau": "XOF",
    "France": "EUR",
    "Belgique": "EUR",
    "Espagne": "EUR",
    "Italie": "EUR",
    "Allemagne": "EUR",
    "Canada": "CAD",
    "États-Unis": "USD",
    "Royaume-Uni": "GBP"
  };
  
  return currencyMap[country] || "XAF";
};

export const convertCurrency = (amount: number, fromCurrency: string, toCurrency: string): number => {
  // Fixed exchange rates for demo purposes
  const rates: { [key: string]: number } = {
    "XAF": 1,
    "XOF": 1, // Same value as XAF
    "EUR": 655.957,
    "USD": 600,
    "CAD": 450,
    "GBP": 750
  };
  
  if (fromCurrency === toCurrency) return amount;
  
  const fromRate = rates[fromCurrency] || 1;
  const toRate = rates[toCurrency] || 1;
  
  return (amount / fromRate) * toRate;
};

export const formatCurrency = (amount: number, currency: string): string => {
  const locale = currency === "EUR" ? "fr-FR" : 
                currency === "USD" ? "en-US" :
                currency === "CAD" ? "fr-CA" :
                currency === "GBP" ? "en-GB" : "fr-FR";
  
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

// Fee calculation function with fixed rates
export const calculateFee = (
  amount: number, 
  senderCountry: string = "any", 
  recipientCountry: string = "any", 
  userRole: string = "user"
): {
  fee: number;
  rate: number;
  agentCommission: number;
  moneyFlowCommission: number;
} => {
  // Fixed 6% fee rate for all transfers
  const rate = 0.06;
  const fee = amount * rate;
  
  // Commission breakdown
  let agentCommission = 0;
  let moneyFlowCommission = fee;
  
  if (userRole === 'agent') {
    // Agent gets 2% commission (1/3 of the 6% fee)
    agentCommission = fee * (2/6); // 2% of original amount
    moneyFlowCommission = fee * (4/6); // 4% of original amount
  }
  
  return {
    fee,
    rate,
    agentCommission,
    moneyFlowCommission
  };
};
